#!/bin/sh

if [ $(cat /etc/hosts|grep "fdf0:9bb:7814:a630::007"|wc -l) -eq 0 ]; then
	echo "fdf0:9bb:7814:a630::007 firmware.fffr" >> /etc/hosts
fi
if [ $(cat /etc/hosts|grep "10.60.5.110"|wc -l) -eq "0" ]; then
        echo "10.60.5.110 firmware.fffr" >> /etc/hosts
fi
if [ $(cat /etc/hosts|grep "2001:470:25:713::2"|wc -l) -eq 0 ]; then
	echo "2001:470:25:713::2 openfreiburg.de" >> /etc/hosts
fi
if [ $(cat /etc/hosts|grep "178.254.39.111"|wc -l) -eq 0 ]; then
        echo 178.254.39.111 openfreiburg.de >> /etc/hosts
fi
if [ $(cat /etc/hosts|grep "fdf0:9bb:7814:a630::b45b"|wc -l) -eq 0 ]; then
        echo "fdf0:9bb:7814:a630::b45b 1.updates.services.fffr" >> /etc/hosts
fi

